### ISSUE TITLE
Enable build for py35

### ISSUE THREAD

**Issue by xmnlab** [conda-forge/pymapd-feedstock#16]
Currently the CF doesn't build for python 3.5. That would be great to have py35 builds.

Maybe it could be done adding `min_py_ver: '35'` on https://github.com/conda-forge/pymapd-feedstock/blob/master/conda-forge.yml

**Comment by randyzwitch** [comment]
The min technically is 2.7, until we stop supporting it. We're planning on removing 2.7 support soon, but it may persist for a few more releases.

**Comment by xmnlab** [comment]
I asked that on CF gitter channel and I receive this answer: `py35 is no longer supported by conda-forge`
