### ISSUE TITLE
Updating toolchain for Python 3.7, Arrow 0.11 and removing Cython

### ISSUE THREAD

**Issue by randyzwitch** [conda-forge/pymapd-feedstock#17]
We're about to cut a new release v0.7.0, which now supports python 3.7 and pyarrow 0.11.0. It also removes the need for Cython to compile the package, instead opting for using the ctypes package to do IPC.

@xhochy I'm not exactly sure what I need to update here, especially around the compiler changes that were reverted about a month ago. Is this something you can help with?

**Comment by xhochy** [comment]
Basically it should boil down to:

1. Update the `meta.yaml` with the new version and updated dependencies.
2. Copy the contents of https://github.com/conda-forge/arrow-cpp-feedstock/blob/master/conda-forge.yml into the `conda-forge.yaml` of this repo.
3. Call `conda smithy rerender`

**Comment by randyzwitch** [comment]
Submitted #19. Is there something that updates the version number and the hash?

**Comment by randyzwitch** [comment]
Hmmm #20 just triggered automatically. That updates the version number, but doesn't incorporate the cython and pyarrow changes I have here
