### ISSUE TITLE
Conda not solving as desired

### ISSUE THREAD

**Issue by randyzwitch** [conda-forge/pymapd-feedstock#27]
Issue: 

From a clean environment, getting a conflict that feels like it shouldn't be an issue. I want conda to solve pymapd=0.7.1 with pyarrow=0.10.*, so that cudf will install. pymapd and cudf work together locally (where pymapd is developed using `pip install -e`), I just need to understand how to get the conda recipe correct.

cudf is upgrading to pyarrow 0.11 shortly I believe (due to the compiler updates), but I don't want to depend on them.

```python
randyzwitch@laptop:~$ conda create -n unsatisfiable
Solving environment: done

## Package Plan ##

  environment location: /home/randyzwitch/miniconda3/envs/unsatisfiable


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate unsatisfiable
#
# To deactivate an active environment, use
#
#     $ conda deactivate

randyzwitch@laptop:~$ conda activate unsatisfiable
(unsatisfiable) randyzwitch@laptop:~$ conda install -c conda-forge -c nvidia -c rapidsai -c numba -c defaults pymapd=0.7.1 cudf=0.4 python=3.6
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - cudf=0.4
  - pymapd=0.7.1 -> arrow-cpp[version='>=0.10,<0.12,>=0.11.1,<0.12.0a0'] -> boost-cpp[version='>=1.68.0,<1.68.1.0a0']
Use "conda info <package>" to see the dependencies for each package.
```

@xhochy Since you work on Arrow, any ideas? Are we over-specifying arrow-cpp in the recipe?
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xhochy** [comment]
Ah, we get to know all the new features conda introduced in the last weeks.

You need to remove any references to arrow-cpp in the meta.yml. Packages that directly depend on arrow-cpp have a more stricker pinning introduced during the build by the arrow-cpp recipe. As this is only Python code, it should only depend on pyarrow.
