### ISSUE TITLE
Remove Python 2, add Arrow 0.12

### ISSUE THREAD

**Issue by randyzwitch** [conda-forge/pymapd-feedstock#29]
The newest release of pymapd, 0.8, sent to PyPI today with Python 2 support removed. Added Arrow 0.12. Putting note here to update when the bot opens a PR later today.

**Comment by randyzwitch** [comment]
I updated the upper limit for pyarrow to `<0.13` on the #30 PR, but I don't see where to disable Python 2 support. @xhochy can you help when you get a chance?

**Comment by xmnlab** [comment]
hey @randyzwitch! 

maybe you can use this approach: 

https://github.com/conda-forge/conda-forge.github.io/issues/486#issuecomment-362961765
